# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
name: Build and Test Flutter Code

on:
  repository_dispatch:
    types:
      - build-and-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v5
        with:
          flutter-version: '2.x'  # Adjust to your Flutter version

      - name: Build Flutter Code
        run: flutter build apk  # Adjust the build command as needed

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
        run: dart test
