name: Test flutter code

on:
  
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Source Repository Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }} # Replace with your PAT
          repository: Hassanajmalcowlar/appiumFramworksPOC
          event-type: build-and-test
      - name: Poll Test Workflow Status
        run: |
          while true; do
            status=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            -u ${{ secrets.GITHUB_TOKEN }} \
            https://api.github.com/repos/Hassanajmalcowlar/appiumFramworksPOC/actions/workflows/test.yml/runs/latest | jq -r '.status')
            echo "Test Workflow Status: $status"
            if [ "$status" == "completed" ]; then
              break
            fi
            sleep 30  # Adjust the polling interval as needed
          done    
